config/routes.rb
Rails.application.routes.draw do

  #顧客用
  #URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do

  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :cart_items, only: [:new, :create, :show, :index, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :customers, only: [:new, :edit, :show]

  get 'customer/top', to: 'customers#top'

  post 'orders/confirm', to: 'orders#confirm'

  get 'complete', to: 'orders#complete'

  patch 'customer/my_page', to: 'customers#update', as: 'customer_my_page'

  get 'customer/sign_in', to: 'customers#new'
    #顧客サインイン後のマイページへの遷移
  get 'customer/information/edit', to: 'customers#edit'
    #顧客情報編集画面への遷移
  get 'customer/orders', to: 'customers#index'

  get 'customer/confirm', to: 'customers#confirm'

  patch 'customer/:id/withdraw', to: 'customers#withdraw',as: 'customer_withdraw'
    #顧客の退会ステータス
  delete 'destroy_all_cart_items', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'

  end




  #管理者用
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
  get 'top', to: 'homes#top'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :orders, only: [:index, :show]

  delete 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_session

  #delete 'sign_out', to: 'sessions#destroy_admin_session', as: :destroy_admin_session
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
    flash[:success] = '個人情報を編集しました'
    redirect_to admin_customer_path(@customer.id)
    else
    flash[:danger] = '個人情報の編集に失敗しました'
    render :edit
    end
  end



  #ストロングパラメータ
  private

  def customer_params
    params.require(:customer).permit(:id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :telephone_number, :email, :address, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
<h3>会員情報編集画面</h3>
  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true, method: :patch do |f| %>

<table class="table">
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= f.text_field :last_name, value: @customer.last_name %> <%= f.text_field :first_name, value: @customer.first_name %></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td><%= f.text_field :last_name_kana, value: @customer.last_name_kana %> <%= f.text_field :first_name_kana, value: @customer.first_name_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= f.text_field :postal_code, value: @customer.postal_code %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= f.text_field :telephone_number, value: @customer.telephone_number %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= f.text_field :email, value: @customer.email %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= f.text_field :address, value: @customer.address %> </td>
  </tr>
  <tr>
    <td>会員ステータス<td>
      <%= f.label :is_active, '有効', value: true %>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '退会', value: false %>
      <%= f.radio_button :is_active, false %>
  </tr>
</table>

<%= f.submit '変更を保存', class: 'btn btn-success', data: { confirm: '情報を登録してもよろしいですか？' } %>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2>会員一覧</h2>


  <table class="table">
  <tr>
    <th>会員ID</th>
    <th>氏名</th>
    <th>メールアドレス</th>
    <th>ステータス</th>
  </tr>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td><%= link_to customer.last_name +
        customer.first_name, admin_customer_path(customer.id), style: "color: black; text-decoration: underline;" %></td>
      <td><%= customer.email %></td>
      <td>
        <% if customer.is_active == true %>
          <span class="text-success">有効</span>
        <% elsif customer.is_active == false %>
          <span class="text-secondary">退会</span>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
<h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h2>


<table class="table">
  <tr>
    <td>会員ID</td>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td><%= @customer.last_name %></td>
    <td><%= @customer.first_name %></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td><%= @customer.last_name_kana %></td>
    <td><%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <td>会員ステータス</td>
    <td><% if @customer.is_active == true %>
    <span class="text-success mt-3">有効</span></td>
    <td><% elsif @customer.is_active == false %>
    <span class="text-secondary mt-3">退会</span></td>
      <% end %>
  </tr>
</table>

<%= link_to '編集する', edit_admin_customer_path, class: 'btn btn-success' %>
<%= link_to '注文履歴一覧を見る', admin_top_path, class: 'btn btn-primary' %>