config/routes.rb
Rails.application.routes.draw do

  #顧客用
  #URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do

  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :cart_items, only: [:new, :create, :show, :index, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :customers, only: [:new, :edit, :show]

  get 'customer/top', to: 'customers#top'

  post 'orders/confirm', to: 'orders#confirm'

  get 'complete', to: 'orders#complete'

  patch 'customer/my_page', to: 'customers#update', as: 'customer_my_page'

  get 'customer/sign_in', to: 'customers#new'
    #顧客サインイン後のマイページへの遷移
  get 'customer/information/edit', to: 'customers#edit'
    #顧客情報編集画面への遷移
  get 'customer/orders', to: 'customers#index'

  get 'customer/confirm', to: 'customers#confirm'

  patch 'customer/:id/withdraw', to: 'customers#withdraw',as: 'customer_withdraw'
    #顧客の退会ステータス
  delete 'destroy_all_cart_items', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'

  end




  #管理者用
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
  get 'top', to: 'homes#top'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :orders, only: [:index, :show]

  delete 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_session

  #delete 'sign_out', to: 'sessions#destroy_admin_session', as: :destroy_admin_session
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

    enum payment_method: { credit_card: 0, transfer: 1 }

    belongs_to :customer
    has_many :order_details
    has_many :items, through: :ordered_details #注文には商品が複数ある

 enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4,
 }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def show
    @order = Order.find(params[:id]) #オーダー情報を全て入れる
    @order_details = @order.order_details
    @payment_method = params[:order] ? params[:order][:payment_method] : nil
    @customer = @order.customer # オーダーした購入者の情報を取得する
    @postage = 800

  end

private

  def order_params
    params.require(:order).permit(:postal_code, :address, :delively_name, :payment_method)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h2>注文履歴詳細</h2>

  <table class="table">
    <tr>
      <td>購入者</td>
      <td><%= link_to @order.delively_name, admin_customer_path(@customer.id), style: 'color: inherit' %></td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at %></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td><%= @order.postal_code %> <%= @order.address %> <%= @order.delively_name %> </td>
    </tr>
    <tr>
      <td>支払方法</td>
      <% if @payment_method == 'credit_card' %>
        <td>クレジットカード</td>
      <% else %>
        <td>銀行振込</td>
      <% end %>
    </tr>
  </table>

  <table class="table">
    <tr>
      <td>商品名</td>
      <td>単価(税込)</td>
      <td>数量</td>
      <td>小計</td>
    </tr>


    <% subtotal = 0 %>
    <% @order_details.each do |order_detail| %>
      <% subtotal += (order_detail.price * 1.1).to_i * (order_detail.quentity) %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= (order_detail.price * 1.1).to_i %></td>
        <td><%= order_detail.quentity %></td>
        <td><%= (order_detail.price * 1.1).to_i * order_detail.quentity %></td>
      </tr>
    <% end %>
  </table>


  <table class="total_table">
    <tr>
      <td>商品合計</td>
      <td colspan="3"></td>
      <td><%= subtotal %></td>
    </tr>
      <td>送料</td>
      <td colspan="3"></td>
      <td><%= @postage %></td>
    <tr>
      <td>請求合計金額</td>
      <td colspan="3"></td>
      <td><%= subtotal + @postage %></td>
    </tr>
  </table>
</div>