config/routes.rb
Rails.application.routes.draw do

  #顧客用
  #URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do

  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :cart_items, only: [:new, :create, :show, :index, :update, :destroy]
  resources :orders, only: [:new, :create, :index, :show]
  resources :customers, only: [:new, :edit, :show]

  get 'customer/top', to: 'customers#top'

  post 'orders/confirm', to: 'orders#confirm'

  get 'complete', to: 'orders#complete'

  patch 'customer/my_page', to: 'customers#update', as: 'customer_my_page'

  get 'customer/sign_in', to: 'customers#new'
    #顧客サインイン後のマイページへの遷移
  get 'customer/information/edit', to: 'customers#edit'
    #顧客情報編集画面への遷移
  get 'customer/orders', to: 'customers#index'

  get 'customer/confirm', to: 'customers#confirm'

  patch 'customer/:id/withdraw', to: 'customers#withdraw',as: 'customer_withdraw'
    #顧客の退会ステータス
  delete 'destroy_all_cart_items', to: 'cart_items#destroy_all', as: 'destroy_all_cart_items'

  end




  #管理者用
  #URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
  get 'top', to: 'homes#top'
  resources :customers, only: [:index, :show, :edit, :update]
  resources :items, only: [:new, :create, :show, :index, :edit, :update]
  resources :orders, only: [:index, :show]

  delete 'admin/sign_out', to: 'admin/sessions#destroy', as: :destroy_admin_session

  #delete 'sign_out', to: 'sessions#destroy_admin_session', as: :destroy_admin_session
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord


  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items
end

app/models/order.rb
class Order < ApplicationRecord

    enum payment_method: { credit_card: 0, transfer: 1 }

    belongs_to :customer
    has_many :order_details
    has_many :items, through: :ordered_details #注文には商品が複数ある

 enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4,
 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item #ここでorderとorder_detailを結び付けているためorder_detail.item.nameとかで呼び出せる
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.includes(:order_details).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    #@item.image.attach
  end

  # 商品の詳細画面表示
  def show
    @item = Item.find(params[:id])
  end

  # 投稿データの保存
  def create
    @item = Item.new(item_params)
    if params[:item][:image].present?
      @item.image.attach(params[:item][:image])
    else
      @item.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'no_image.jpg')), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
  if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  else
    render :edit
  end
  end



  # 投稿データのストロングパラメータ
  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image, :edit)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def show
    @order = Order.find(params[:id]) #オーダー情報を全て入れる
    @order_details = @order.order_details
    @payment_method = params[:order] ? params[:order][:payment_method] : nil
    @customer = @order.customer # オーダーした購入者の情報を取得する
    @postage = 800

  end

private

  def order_params
    params.require(:order).permit(:postal_code, :address, :delively_name, :payment_method)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  before_action :authenticate_admin!
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/1084fc60d7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <% if customer_signed_in? %>
          <nav class="navbar navbar-expand d-flex">
          <ul class="navbar-nav">
            <li class="nav-item mr-10"><%= link_to "LOGO", top_path, style: "color: black" %></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-5"><%= link_to "マイページ", customer_path(current_customer.id), style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "商品一覧", items_path, style: "color: black" %></li><!-- pathは未設定 -->
            <li class="nav-item mr-5"><%= link_to "カート", cart_items_path, style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, style: "color: black" %></li>
          </ul>
          </nav>
          <div class="text-center">
            <p>ようこそ、<%= current_customer.last_name +  current_customer.first_name %>さん！</p>
          </div>
        <% elsif admin_signed_in? %>
          <nav class="navbar navbar-expand d-flex">
          <ul class="navbar-nav">
            <li class="nav-item mr-10"><%= link_to "LOGO", top_path, style: "color: black" %></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-5"><%= link_to "商品一覧", admin_items_path, style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "会員一覧", admin_customers_path, style: "color: black" %></li><!-- pathは未設定 -->
            <li class="nav-item mr-5"><%= link_to "注文履歴一覧", admin_top_path, style: "color: black" %></li><!-- pathは未設定 -->
            <li class="nav-item mr-5"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, style: "color: black", data: { confirm: 'ログアウトしてもよろしいですか？' } %></li>
          </ul>
          </nav>
        <% else %>
          <nav class="navbar navbar-expand d-flex">
          <ul class="navbar-nav">
            <li class="nav-item mr-10"><%= link_to "LOGO", top_path, style: "color: black" %></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-5"><%= link_to "About", about_path, style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "商品一覧", items_path, style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "新規登録", new_customer_registration_path, style: "color: black" %></li>
            <li class="nav-item mr-5"><%= link_to "ログイン", new_customer_session_path, style: "color: black" %></li>
          </ul>
          </nav>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>